name: Continuous Integration
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.7.0
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Save dist to artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist

  tests:
    runs-on: ubuntu-22.04
    needs: build
    container:
      image: cypress/browsers:node-22.7.0-chrome-127.0.6533.119-1-ff-129.0.1-edge-127.0.2651.98-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.7.0
          cache: "npm"

      - name: Download production build
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist

      # Runs test using production build
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          browser: chrome

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.7.0
          cache: "npm"

      - name: Download production build
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist

      - name: Install Cloudflare CLI
        run: npm install -g wrangler@4.13.1

      - name: Deploy to Cloudflare Pages
        run: |
          wrangler pages deploy ./dist  \
            --project-name=portfolio \
            --branch=master \
            --commit-hash="${{ github.sha }}" \
            --commit-message="${{ github.event.head_commit.message }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
