name: Continuous Integration
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 22
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service nginx
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEPLOY }}

      - name: Clear cache from cloudflare
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache
          configuration: '{ "method": "POST", "headers": { "Authorization": "Bearer ${{ secrets.CLOUDFLARE_API_KEY }}", "Content-Type": "application/json" }, "body": { "purge_everything": true }'
