name: Continuous Integration
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-22.7.0-chrome-127.0.6533.119-1-ff-129.0.1-edge-127.0.2651.98-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 22.7.0
      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run preview

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Cloudflare CLI
        run: npm install -g wrangler@4.13.1

      - name: Deploy to Cloudflare Pages
        run: wrangler pages publish ./dist  \
          --project-name=portfolio \
          --branch=master \
          --commit-hash=${{ github.sha }} \
          --commit-message=${{ github.event.head_commit.message }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
