name: Continuous Integration
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-22.7.0-chrome-127.0.6533.119-1-ff-129.0.1-edge-127.0.2651.98-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "Using node $(node -v)"
      - run: echo "Using npm $(npm -v)"

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run preview

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 22
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      # In this step we build a new version using Dockerfile
      - name: Deploy
        run: railway up --service nginx
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEPLOY }}

      - name: Clear cache from cloudflare
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache
          configuration: '{ "method": "POST", "headers": { "Authorization": "Bearer ${{ secrets.CLOUDFLARE_API_KEY }}", "Content-Type": "application/json" }, "body": { "purge_everything": true }}'
